name: xibo-player
base: core24
adopt-info: app
summary: Xibo Linux Player
description: Xibo for Linux Digital Signage Player
confinement: strict
grade: devel

apps:
  xibo-player:
    extensions: [gnome]
    command: xibo-player --no-sandbox
    plugs:
      - browser-support
      - home 
      - network
      - network-bind
      - opengl
      - audio-playback
      - screen-inhibit-control
      - x11
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      LIBGL_ALWAYS_SOFTWARE: '0'
      # Force the loader to look in the internal library path first
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH

parts:
  app:
    plugin: dump
    source: . 
    source-subdir: out/xibo-player-linux-x64
    # STRATEGY: Move custom libraries into the standard system path
    # This prevents 'not found' errors because the loader checks here by default.
    organize:
      libOSSlib.so: usr/lib/x86_64-linux-gnu/libOSSlib.so
      libpxbackend-1.0.so: usr/lib/x86_64-linux-gnu/libpxbackend-1.0.so
    
    stage-packages:
      # Use the 't64' versions for Core24/Ubuntu 24.04 compatibility
      - libglib2.0-0t64
      - libproxy1v5            
      - glib-networking        
      - libnss3
      - libnspr4
      - libatk1.0-0t64
      - libatk-bridge2.0-0t64
      - libcups2
      - libdrm2
      - libxkbcommon0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxrandr2
      - libgbm1
      - libasound2t64
      - libpangocairo-1.0-0
      - libpango-1.0-0
      - libcairo2
      - libgtk-3-0t64
      - libgl1

    build-packages:
      - jq
    override-pull: |
      craftctl default
      # We use $SNAPCRAFT_PROJECT_DIR to ensure we find package.json 
      # regardless of the 'source' setting of this specific part
      VERSION=$(jq -r .version "$SNAPCRAFT_PROJECT_DIR/package.json")
      craftctl set version=$VERSION
