name: xibo-electron
base: core22
version: '0.1'
summary: Xibo Linux Player
description: Xibo for Linux Digital Signage Player
confinement: strict
grade: devel

apps:
  xibo-electron:
    extensions: [gnome]
    command: xibo-electron --no-sandbox
    plugs:
      - browser-support
      - home 
      - network
      - network-bind
      - opengl
      - audio-playback
      - screen-inhibit-control
      - x11
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      LIBGL_ALWAYS_SOFTWARE: '0' 

parts:
  app:
    plugin: dump
    source: out/xibo-electron-linux-x64 
    stage-packages:
      - libnss3
      - libasound2
      - libgbm1
      - libgl1-mesa-dri
      - libgl1-mesa-glx